Feat/import and export
brukri/simple-notes pull request #12
Opened 2023-06-12 07:56 UTC by NinoHelfenstein

added csv and json import and export

2023-06-20 09:12 UTC, brukri requested changes

2023-06-20 09:12 UTC, brukri commented on src/controller.js
> -    const newNode = existingNoteTemplate.cloneNode(true);
Please keep naming as it is a DOM-node

2023-06-20 09:12 UTC, brukri commented on src/controller.js
> +    const newNote = existingNoteTemplate.cloneNode(true);
Maybe prefer `node` here as well.

2023-06-20 09:12 UTC, brukri commented on src/controller.js
> +    var notes = JSON.parse(localStorage.getItem(SIMPLE_NOTES_STORAGE_KEY));
Prefer `const` or `let` instead of `var`

2023-06-20 09:12 UTC, brukri commented on src/controller.js
> +      console.log("csvFile");
Remove `console.log`

2023-06-20 12:22 UTC, NinoHelfenstein commented
@brukri

2023-06-23 08:22 UTC, NinoHelfenstein commented
@brukri all requested changes made

2023-06-23 09:36 UTC, brukri approved these changes

2023-06-26 12:22 UTC, merged